[package]
name = "actix-ws"
description = "Websockets for the Actix runtime, without Actors"
version = "0.2.1"
authors = ["asonix <asonix@asonix.dog>"]
readme = "README.md"
repository = "https://git.asonix.dog/asonix/actix-actorless-websockets"
license = "MIT/Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["examples/chat"]

[dependencies]
actix-http = { version = "3.0", default-features = false, features = ["ws"] }
actix-web = { version = "4.0", default-features = false }
bytes = "1.0"
futures-util = "0.3"
pin-project = "1"
thiserror = "1.0"
tokio = { version = "1", features = ["sync", "io-util"] }
tokio-util = { version = "0.7", features = ["codec"] }
